# Generated by Django 4.2.3 on 2023-07-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
